program: src/mlops_project/train.py
method: bayes
metric:
  name: val_acc
  goal: maximize

parameters:
  hyperparameters.batch_size:
    values: [16, 32, 64]
  hyperparameters.lr:
    distribution: log_uniform_values
    min: 0.0001
    max: 0.01
  hyperparameters.hidden_size:
    values: [32, 64, 128]
  hyperparameters.num_layers:
    values: [1, 2, 3]
  hyperparameters.dropout:
    distribution: uniform
    min: 0.1
    max: 0.5
  hyperparameters.seq_len:
    values: [5, 10, 15]
  hyperparameters.epochs:
    value: 10

# Disabled early termination to let all runs complete
# early_terminate:
#   type: hyperband
#   min_iter: 3
