hyperparameters:
  batch_size: 8
  epochs: 10
  lr: 0.001
  hidden_size: 32
  num_layers: 1
  dropout: 0.2
  seq_len: 10

training:
  train_split: 0.8
  seed: 42

paths:
  dataset: "data/processed/sample_data.csv"
  model_dir: "models"

wandb:
  project: "football-lstm"
  entity: "tyranguyen7-danmarks-tekniske-universitet-dtu"
  mode: "online"
